enum class PayloadType : unsigned int
{
	CLIENT_AUTHENTICATION,
    CLIENT_AUTHENTICATION_APPROVED,
	CLIENT_AUTHENTICATION_REJECTED,
    SERVER_GET_DB_NAMES,
    SERVER_GET_DB_COLLECTIONSNAMES,
	SERVER_GET_DB_DATA_ERROR,
	SERVER_GET_ALL_USERS_IN_DATABASE,

	SERVER_ADD_USER_TO_DATABASE,
	SERVER_ADD_USER_TO_DATABASE_SUCCESS,
//	SERVER_USER_ALREADY_ADDED_TO_DATABASE,
	SERVER_USER_ADD_TO_DATABASE_ERROR,

    SERVER_DELETE_USER,
    SERVER_USER_DELETION_SUCCESS,
    SERVER_USER_DELETION_ERROR,

    SERVER_MODIFY_USER_INFO,
    SERVER_MODIFY_USER_INFO_SUCCESS,
    SERVER_MODIFY_USER_INFO_ERROR

};
